### ISSUE TITLE
get() is including extra object path information in the local path after upgrading to version 2023.3.0

### ISSUE THREAD

**Issue by gmweaver** [fsspec/s3fs#717] opened 2023-03-31 16:41 UTC
After upgrading from 2022.11.0 to 2023.3.0, I am seeing different behavior when copying a list of remote paths to a local directory via `get`. Specifically, it seems to be including extra object path data in the final local path (looks like only one level up).

As an example, assume I am copying a set of files to local.

```
import os

import s3fs

remote_objs_to_copy = [
    "s3://my-bucket/path/to/some_data/data1.parquet", 
    "s3://my-bucket/path/to/some_data/data2.parquet",
]
target_local_dir = "/tmp/testing_s3fs/"

s3fs.S3FileSystem(...).get(remote_objs_to_copy, target_local_dir)
```

Running `os.listdir(target_local_dir)`.

v2022.11.0 returns: 

`["/tmp/testing_s3fs/data1.parquet", "/tmp/testing_s3fs/data2.parquet"]`

v2023.3.0 returns: 

`[some_data]`

Listing files under `some_data`, `os.listdir(f"{target_local_dir}/some_data")`, I do see the files.

**Comment by ianthomas23** [comment] 2023-03-31 18:01
I cannot reproduce this, see new PR (https://github.com/fsspec/s3fs/pull/718) that behaves as expected, i.e. does not include an extra directory.

@gmweaver:

1. Can you post your `pip list` or `conda list` to confirm that you have consistent versions of `fsspec` and `s3fs` installed?
2. Your `v2022.11.0` listing in your original post is of the `s3` filesystem not the `local` one. Can you check this please.

**Comment by gmweaver** [comment] 2023-03-31 19:16
1. We use `pip-compile` and the generated requirements file has:

```
fsspec==2023.3.0
```

2. Apologies, that is a typo, updated initial post with correct file paths.

Can a test be added where there is an ending slash: `target = os.path.join(tmpdir, "target/")`

**Comment by gmweaver** [comment] 2023-03-31 19:40
Also, tried to run the suggested test above locally, but I run into errors that look related to mocking boto/s3:

```
python -m venv venv
pip install -r requirements.txt -r test_requirements.txt
pytest
```

I see `ERROR s3fs/tests/test_mapping.py::test_simple - botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://127.0.0.1:5555/test"`

**Comment by ianthomas23** [comment] 2023-04-01 16:33
Ah yes, my mistake. With the trailing slash on the target directory I can reproduce this, the `some_data` directory is created and it shouldn't be.

We've done quite a bit of work recently to ensure that `cp`, `get` and `put` are correct and consistent. I am reasonably sure that this is all correct for single file and single directory copying but we haven't got round to the multiple file cases yet. Evidently we don't have an explicit test for this situation and it has changed as a result of the other changes.

**Comment by LeeMendelowitz** [comment] 2023-04-04 03:40
I have a different reproducible example for what I think is the same issue. The behavior changed between `s3fs==2023.1.0` and `s3fs==2023.3.0`.

```python
from pathlib import Path
import s3fs
import tempfile
fs = s3fs.S3FileSystem()

# 1. Upload files to the bucket destination.
bucket_destination = 'my-bucket/storage_test'
with tempfile.TemporaryDirectory() as tmpdir:
    output_file = Path(tmpdir) / 'file.txt'
    with output_file.open('w') as fout:
        fout.write('hi\n')
    fs.put(str(output_file), bucket_destination + '/file.txt')
    fs.put(str(output_file), bucket_destination + '/file2.txt')



# 2. Download files from the bucket destination into the current directory.
#  - With s3fs==2023.1.0, files "file1.txt" and "file2.txt" are created in "." (current directory)
#  - With s3fs==2023.3.0, files "file1.txt" and "file2.txt" are created in "./storage_test"
fs.get(bucket_destination, '.', recursive=True)
```

**Comment by tracek** [comment] 2023-07-03 12:23
@ianthomas23 Is there any way to get the came `get` behaviour in `s3fs=2023.6.0` as in `2023.1.0` when it comes to copying the directory tree? In the old version I could pass a list of files in different "subdirectories" on S3 and have the structure recreated locally. In the new version they are all copied to a destination directory, without maintaining the structure (which results for me in overwritten files and lost structure). I thought `recursive` parameter on `get` would maintain the structure, but that does not appear to be the case.

Is there a way I can copy multiple files at once with `2023.6.0` while maintaining the source directory structure?

**Comment by ianthomas23** [comment] 2023-07-04 10:01
@tracek Copying a list of named files to a directory is working as expected (https://filesystem-spec.readthedocs.io/en/latest/copying.html#multiple-source-to-single-target). Just as with command-line `cp` the directory structures of the source files is irrelevant, they are all copied into the target directory. `recursive` makes no difference, it only affects the expansion of wildcards and directories in the source file list.

If you are copying lists of directories and or globs then it is entirely possible that it is not working correctly. If the scenario is not listed at https://filesystem-spec.readthedocs.io/en/latest/copying.html then we make no claim that it is working correctly yet.

Can you post a specific example (with code) of what you are attempting, what the outcome is and what you think it should be? And can you do so in a new issue rather than in this issue that I am about to close as it has been fixed. Thanks!

**Comment by ianthomas23** [comment] 2023-07-04 10:02
I am closing this issue as the original report is working as expected, as described at https://filesystem-spec.readthedocs.io/en/latest/copying.html.

**Closed by ianthomas23** 2023-07-04 10:02 UTC

**Comment by martindurant** [comment] 2023-07-04 13:12
@tracek - if you wish to copy your list of paths to specific locations, you can pass a list as the "to" path argument of the same length as the origin list. Perhaps you can create this to list with a simple comprehension
```
to_path = [p.replace(origin_root, out_root) for p in paths]
```

**Comment by tracek** [comment] 2023-07-04 17:19
Thanks gentleman!

@ianthomas23 Great to know, only now I realised that reading the code & docs of `fsspec` is instrumental for better understanding how `s3fs` works. Indeed my case, i.e. multiple destinations, is not listed there.

Still, what @martindurant mentioned (thanks!) works like a charm. Not knowing this, I had to resort to bunch of async `_get_file` tasks. Maybe it's something worth documenting? If you think it makes sense and could use extra pair of hands, I am happy to make a PR. 

BTW, is `batch_size` a valid parameter for `get`?

**Comment by martindurant** [comment] 2023-07-04 17:33
> Maybe it's something worth documenting? 

The documentation can always be better, and help is appreciated. As you can see, there are lots of possible ways to call methods, so it is tricky to present all the options and information in a coherent manner.

> is batch_size a valid parameter for get?

It should be: the number of requests in flight at one time.

**Comment by tracek** [comment] 2023-07-04 19:14
> > is batch_size a valid parameter for get?
> 
> It should be: the number of requests in flight at one time.

In my testing it did not matter if I set it `batch_size=1` or `batch_size=-1`, I'd always get unthrottled version (evidenced by all files created and downloaded at the same time). Initially I thought of raising an issue, but then it's not documented in s3fs docs, so hardly an issue in itself.

I understand the need for concise docs. Thanks for help!
