### ISSUE TITLE
s3fs creates a bucket even when one already exists, when using pandas.DataFrame.to_csv

### ISSUE THREAD

**Issue by tekumara** [fsspec/s3fs#451] opened 2021-03-31 08:10 UTC
**What happened**:

s3fs creates a bucket even when one already exists, when using `pandas.DataFrame.to_csv`

**What you expected to happen**:

A bucket should not be created when one already exists so that:
1) Users that have not been granted the s3:CreateBucket action can still write objects to the bucket
2) The CreateBucket event is not triggered unnecessarily. This can be a problem for automatic processes that run on the CreateBucket event, like bucket tagging or compliance checks, that shouldn't run on existing buckets.

**Minimal Complete Verifiable Example**:

```python
$ pip install pandas==1.2.3 s3fs==0.5.2
...
$ python
Python 3.7.9 (default, Oct 14 2020, 16:19:52)
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd; df = pd.DataFrame(["foo","bar"])
>>> df.to_csv("s3://oliver-delete-me-test/foowrite.csv")
Traceback (most recent call last):
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/s3fs/core.py", line 599, in _mkdir
    await self.s3.create_bucket(**params)
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/pandas/core/generic.py", line 3403, in to_csv
    storage_options=storage_options,
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 234, in save
    storage_options=self.storage_options,
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/pandas/io/common.py", line 563, in get_handle
    storage_options=storage_options,
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/pandas/io/common.py", line 345, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/fsspec/core.py", line 438, in open
    **kwargs,
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/fsspec/core.py", line 291, in open_files
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/fsspec/core.py", line 291, in <listcomp>
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/s3fs/core.py", line 614, in makedirs
    self.mkdir(path, create_parents=True)
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/fsspec/asyn.py", line 121, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/fsspec/asyn.py", line 100, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/Users/tekumara/.virtualenvs/tmp-36835a7413f0541/lib/python3.7/site-packages/s3fs/core.py", line 603, in _mkdir
    raise translate_boto_error(e) from e
PermissionError: Access Denied
```

**Anything else we need to know?**:

This doesn't happen when using s3fs directly, eg:
```
>>> import s3fs
>>> s3 = s3fs.S3FileSystem()
>>> with s3.open('oliver-delete-me-test/foowrite.csv', 'wb') as f:
...     f.write(2*2**20 * b'a')
```

This doesn't happen in s3f3 0.4.2 because it doesn't implement `make_dirs`.

**Comment by martindurant** [comment] 2021-03-31 13:50
I cannot tell from the traceback what exactly pandas is calling here, but I don't immediately see why it would be different from calling s3fs directly. It it's makedirs (or mkdir(parent=True), then these should indeed ignore the error. Note that it's not necessarily possible to tell whether a bucket exists except by trying to write to it.

**Comment by tekumara** [comment] 2021-04-04 08:59
Yes from the stacktrace it looks like makedirs is being triggered via fsspec, whereas `s3.open` just tries to write the file without calling `fs.makedirs`.

Specifically, pandas calls `fsspec.core.open` which in turn calls [fsspec.core.open_files](https://github.com/intake/filesystem_spec/blob/master/fsspec/core.py#L213) using the default value of `auto_mkdir=True` so [fs.makedirs('oliver-delete-me-test', exist_ok=True)](https://github.com/intake/filesystem_spec/blob/master/fsspec/core.py#L291) runs and calls [s3fs.core._mkdir('oliver-delete-me-test', create_parents=True)](https://github.com/dask/s3fs/blob/fceadc6cb44837e7178ce3447e21da101599d25a/s3fs/core.py#L619) but the path being passed is the bucket, and so `key = ''` which means this condition is True:

```
        if not key or (create_parents and not await self._exists(bucket)):
```

and CreateBucket is attempted. Perhaps 

BTW if needed, could [HeadBucket](https://docs.aws.amazon.com/en_us/AmazonS3/latest/API/API_HeadBucket.html) be used to check whether a bucket exists?

**Comment by martindurant** [comment] 2021-04-04 18:11
OK, got it. So there are a couple of points
- maybe `create_parent=True` is not the best default, but changing this would break the current API
- such a call should not fail, of course
- you are right that there are various ways we could check if the bucket exists, but the trouble is that ListBuckets, ListObjects, HeadBucket are all separate independent permissions, and none of them tied to whether the given user can write to the bucket. The simplest way to ensure that there is a bucket to write to may indeed simply be to try to (re)create it; but then should try to write whether or not that succeeded. *If* the error is bucket-does-not-exist, then we ought to keep the original error from trying to create the bucket. That's quite complicated!

**Comment by tekumara** [comment] 2021-04-05 01:20
Ah right, yes I see what you mean now about the permission! 

I also agree, creating the bucket automatically doesn't seem like the best default. 

Although it appears to be happening not because of `create_parents=True` but because of `auto_mkdir=True` in `fsspec.core.open_files`. Even if `create_parents=False` the bucket would still be created because fsspec calls makedirs with a [path containing the bucket name only](https://github.com/intake/filesystem_spec/blob/master/fsspec/core.py#L291) (no key), hence the condition above is True.

If the default cannot be changed, would it make sense to change the conditional from:
```
        if not key or (create_parents and not await self._exists(bucket)):
```
to
```
        if (create_parents and not await self._exists(bucket)):
```

When `path` is a bucket only (no key), this will cause s3fs to check if the bucket exists using ListObjectsV2. If the user doesn't have ListObjectsV2 permissions, or they do and the bucket doesn't exist, then `self._exists(bucket)` will return False and only then CreateBucket will be attempted.

**Comment by martindurant** [comment] 2021-04-05 19:45
Here is a possible approach, a bit reversed from your model.

First a couple of notes:

- when the key is bucket/path, mkdir(create_parents=True) is exactly equivalent to makedirs(exist_ok=True); *except* that the former maybe could check for the prior existence of the deeper "directory" and error
- mkdir with a bucket-only path is equivalent to makedirs(exist_ok=False)

If we are making a bucket, we should error for no-permission, and also, if exist_ok=False, error for bucket-exists. The return from the call should tell us which is the case.

If we try to create the bucket and fail for no-permission **and**, we should attempt exists() with the current implementation, and, if the call succeeds, pass or raise according to when exists_ok=True, or if the call fails, raise and pass through the error.

**Comment by asclepiusaka** [comment] 2021-07-17 00:26
Hi @martindurant, I run into the same issue.

I don't think the approach you mentioned would solve the pandas issue we have. 

The problem is, We are implementing makedirs with mkdir, so we need to handle both makedirs('s3://bucket/', exist_ok=True) and makedirs('s3://bucket/', exist_ok=False)
The line in question `pandas.df.to_csv('s3://bucket/file.csv')` in turn calls 
`fs.makedirs(parent, exist_ok=True) for parent in parents`
at [here](https://github.com/intake/filesystem_spec/blob/master/fsspec/core.py#L292)

The semantics is basically ensuring the parent directory exist before open files in the directory.
If we implement this with `s3fs.S3FileSystem.mkdir('s3://bucket/', create_parents)`, it means we are not necessary creating a bucket, to be specific, we are ok if bucket are already exist when we call it with `exist_ok=True`, and our currently method will try to create a bucket whatsoever as key here is empty string ''.
I'm thinking we should raise `FileExistException` whenever a bucket exists (which will be handled by [_makedirs's logic ](https://github.com/dask/s3fs/blob/main/s3fs/core.py#L717)) or based on `create_parents`'s value, to try creating bucket or raise exception.
the method code would be like this:
```
    async def _mkdir(self, path, acl="", create_parents=True, **kwargs):
        path = self._strip_protocol(path).rstrip("/")
        bucket, key, _ = self.split_path(path)
        if self._exists(bucket):
            raise FileExistsError("Bucket %s already exists" % bucket)
        else:
            if create_parents:
                if acl and acl not in buck_acls:
                    raise ValueError("ACL not in %s", buck_acls)
                try:
                    params = {"Bucket": bucket, "ACL": acl}
                    region_name = kwargs.get("region_name", None) or self.client_kwargs.get(
                        "region_name", None
                    )
                    if region_name:
                        params["CreateBucketConfiguration"] = {
                            "LocationConstraint": region_name
                        }
                    await self._call_s3("create_bucket", **params)
                    self.invalidate_cache("")
                    self.invalidate_cache(bucket)
                except ClientError as e:
                    raise translate_boto_error(e)
                except ParamValidationError as e:
                    raise ValueError("Bucket create failed %r: %s" % (bucket, e))
            else:
                # raises if bucket doesn't exist, but doesn't write anything
                await self._ls(bucket)
```

In my local dev env this solve the issue of saving csv to s3. Any thoughts?

**Comment by martindurant** [comment] 2021-07-17 01:06
Looks ok on my phone. I suggest making a PR of the changes, with tests showing the desired behaviour - some of which would presumably fail against master.

On July 16, 2021 8:26:17 PM EDT, Saka ***@***.***> wrote:
>Hi @martindurant, I run into the same issue.
>
>I don't think the approach you mentioned would solve the pandas issue
>we have. 
>
>The problem is, We are implementing makedirs with mkdir, so we need to
>handle both makedirs('s3://bucket/', exist_ok=True) and
>makedirs('s3://bucket/', exist_ok=False)
>The line in question `pandas.df.to_csv('s3://bucket/file.csv')` in turn
>calls 
>`fs.makedirs(parent, exist_ok=True) for parent in parents`
>at
>[here](https://github.com/intake/filesystem_spec/blob/master/fsspec/core.py#L292)
>
>The semantics is basically ensuring the parent directory exist before
>open files in the directory.
>If we implement this with `s3fs.S3FileSystem.mkdir('s3://bucket/',
>create_parents)`, it means we are not necessary creating a bucket, to
>be specific, we are ok if bucket are already exist when we call it with
>`exist_ok=True`, and our currently method will try to create a bucket
>whatsoever as key here is empty string ''.
>I'm thinking we should raise `FileExistException` whenever a bucket
>exists (which will be handled by [_makedirs's logic
>](https://github.com/dask/s3fs/blob/main/s3fs/core.py#L717)) or based
>on `create_parents`'s value, to try creating bucket or raise exception.
>the method code would be like this:
>```
>   async def _mkdir(self, path, acl="", create_parents=True, **kwargs):
>        path = self._strip_protocol(path).rstrip("/")
>        bucket, key, _ = self.split_path(path)
>        if self._exists(bucket):
>            raise FileExistsError("Bucket %s already exists" % bucket)
>        else:
>            if create_parents:
>                if acl and acl not in buck_acls:
>                    raise ValueError("ACL not in %s", buck_acls)
>                try:
>                    params = {"Bucket": bucket, "ACL": acl}
>region_name = kwargs.get("region_name", None) or
>self.client_kwargs.get(
>                        "region_name", None
>                    )
>                    if region_name:
>                        params["CreateBucketConfiguration"] = {
>                            "LocationConstraint": region_name
>                        }
>                    await self._call_s3("create_bucket", **params)
>                    self.invalidate_cache("")
>                    self.invalidate_cache(bucket)
>                except ClientError as e:
>                    raise translate_boto_error(e)
>                except ParamValidationError as e:
>          raise ValueError("Bucket create failed %r: %s" % (bucket, e))
>            else:
>           # raises if bucket doesn't exist, but doesn't write anything
>                await self._ls(bucket)
>```
>
>In my local dev env this solve the issue of saving csv to s3. Any
>thoughts?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/s3fs/issues/451#issuecomment-881783434

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by asclepiusaka** [comment] 2021-07-19 18:21
sounds good, let me write some tests and send a PR

**Comment by asclepiusaka** [comment] 2021-07-22 00:18
I've submitted the PR here: https://github.com/dask/s3fs/pull/502
But be advised that actually the test case will pass with the current implementation too, due to a current bug of moto: https://github.com/spulec/moto/issues/1371

**Comment by martindurant** [comment] 2022-04-18 19:52
Let's close this one, since it's old, and @Mahdi-Hosseinali please open a new one showing what you tried to do and the problem you found.

**Closed by martindurant** 2022-04-18 19:52 UTC
