### ISSUE TITLE
API Reference docs no space between attribute name and type

### ISSUE THREAD

**Issue by williamjamir** [fsspec/s3fs#693] opened 2023-01-31 10:02 UTC
In the API reference section, the attribute name and type have no space, giving the wrong impression of the attribute name.
![image](https://user-images.githubusercontent.com/5083518/215727926-2454f718-7d34-476f-8d48-6ab5eb70f4ef.png)
![image](https://user-images.githubusercontent.com/5083518/215729112-70c3d1d5-928a-4ea5-9334-2f172ff4823e.png)

**Comment by ianthomas23** [comment] 2023-01-31 10:11
Thanks @williamjamir. I know what the cause of this is as I fixed the same problem in `fsspec` recently. I'll submit a fix tomorrow.

**Comment by ianthomas23** [comment] 2023-02-02 14:01
Fixed by #697.

**Closed by ianthomas23** 2023-02-02 14:01 UTC
