### ISSUE TITLE
pandas KeyError: 'retries'

### ISSUE THREAD

**Issue by SandyLi2017** [fsspec/s3fs#592] opened 2022-02-09 10:16 UTC
I am using s3fs with pandas to write data computed via AWS EMR notebook exec to a file on AWS S3 but got below error after s3fs upgraded to latest version.

It looks like dependency conflict to me but not sure which version should be right one for pandas, fsspec, aiobotocore and botocore.

Could someone pls help?
Much appreciate.

command: result_pdf.to_csv(filename, index = False, encoding = 'utf-8')
filename = 's3://*/filename'

error info:
An error was encountered:
'retries'
Traceback (most recent call last):
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/pandas/core/generic.py", line 3228, in to_csv
    formatter.save()
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 202, in save
    self._save()
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 324, in _save
    self._save_chunk(start_i, end_i)
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 356, in _save_chunk
    libwriters.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/_libs/writers.pyx", line 69, in pandas._libs.writers.write_csv_rows
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/fsspec/spec.py", line 1460, in write
    self.flush()
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/fsspec/spec.py", line 1496, in flush
    self._initiate_upload()
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/s3fs/core.py", line 1841, in _initiate_upload
    ACL=self.acl,
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/s3fs/core.py", line 1829, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/s3fs/core.py", line 281, in _call_s3
    raise err
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/s3fs/core.py", line 261, in _call_s3
    out = await method(**additional_kwargs)
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/aiobotocore/client.py", line 174, in _make_api_call
    operation_model, request_dict, request_context)
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/aiobotocore/client.py", line 193, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 83, in _send_request
    exception):
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 216, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/mnt2/yarn/usercache/livy/appcache/application_1644393841242_0001/container_1644393841242_0001_01_000001/tmp/1644394265866-0/lib/python3.7/site-packages/botocore/retryhandler.py", line 189, in __call__
KeyError: 'retries'

my current  packages:
aiobotocore (2.1.0)
aiohttp (3.8.1)
aioitertools (0.9.0)
aiosignal (1.2.0)
async-timeout (4.0.2)
asynctest (0.13.0)
attrs (21.4.0)
aws-cfn-bootstrap (2.0)
beautifulsoup4 (4.9.3)
boto (2.49.0)
boto3 (1.19.12)
botocore (1.22.12)
charset-normalizer (2.0.11)
click (7.1.2)
docutils (0.14)
frozenlist (1.3.0)
fsspec (2022.1.0)
idna (3.3)
jmespath (0.10.0)
joblib (1.0.1)
lockfile (0.11.0)
lxml (4.6.2)
multidict (6.0.2)
mysqlclient (1.4.2)
nltk (3.5)
nose (1.3.4)
numpy (1.16.5)
pandas (0.25.1)
pip (9.0.1)
py-dateutil (2.2)
pystache (0.5.4)
python-daemon (2.2.3)
python-dateutil (2.8.2)
python37-sagemaker-pyspark (1.4.1)
pytz (2021.1)
PyYAML (5.4.1)
regex (2021.3.17)
s3fs (2022.1.0)
s3transfer (0.5.1)
setuptools (28.8.0)
simplejson (3.2.0)
six (1.13.0)
tqdm (4.59.0)
typing-extensions (4.0.1)
urllib3 (1.26.8)
wheel (0.29.0)
windmill (1.6)
wrapt (1.13.3)
yarl (1.7.2)

**Comment by martindurant** [comment] 2022-02-09 14:01
Thanks for the post. This is a duplicate of https://github.com/fsspec/s3fs/issues/588 , so closing. There there is a workaround, but we have not solved this yet in general.

**Closed by martindurant** 2022-02-09 14:01 UTC
