### ISSUE TITLE
S3 error : Unable to locate credentials 

### ISSUE THREAD

**Issue by jmleoni** [fsspec/s3fs#558] opened 2021-11-19 16:32 UTC
Hello,

since asynciohttp [v3.8.1](https://github.com/conda-forge/aiohttp-feedstock/commit/94e676be31151745cea34f6f3e0eea095e9ed2c4) was deployed on condaforge 3 days ago while trying to use s3fs with iamRole based credentials in AWS EC2 servers, we are encountering the following errors :

``` 
  File "fastparquet/api.py", line 132, in __init__
  File "fsspec/asyn.py", line 91, in wrapper
  File "fsspec/asyn.py", line 71, in sync
  File "fsspec/asyn.py", line 25, in _runner
  File "s3fs/core.py", line 1128, in _isdir
  File "s3fs/core.py", line 580, in _lsdir
  File "aiobotocore/paginate.py", line 32, in __anext__
  File "aiobotocore/client.py", line 142, in _make_api_call
  File "aiobotocore/client.py", line 161, in _make_request
  File "aiobotocore/endpoint.py", line 77, in _send_request
  File "aiobotocore/endpoint.py", line 71, in create_request
  File "aiobotocore/hooks.py", line 27, in _emit
  File "aiobotocore/signers.py", line 16, in handler
  File "aiobotocore/signers.py", line 63, in sign
  File "botocore/auth.py", line 373, in add_auth
botocore.exceptions.NoCredentialsError: Unable to locate credentials
 ```
It seems that fixing aiohttp in version v3.7.4.post0 solves this issue.

Not also that we are not encountering the same errors on the same codebase on tasks that are running on Fargate instead of EC2.

I guess it would be good to investigate what happened with aiohttp (which is required by aiobotocore)

Any better solution than fixing aiohttp version is welcome !

**Comment by martindurant** [comment] 2021-11-19 16:41
lease cross-post to aiobotocor and/or botocore - they might be aware of this.

**Comment by martindurant** [comment] 2021-11-19 19:42
PS: worth trying whether using boto directly works, or causes the same exception.

**Comment by achimgaedke** [comment] 2021-11-22 06:27
I stumbled into this issue while using S3 for a [dvc remote](https://dvc.org/doc/command-reference/remote/add#supported-storage-types) storage.

I isolated the failure to `s3fs`, a test with boto did not fail -  test code below. Changing the requirement for `aiohttp<3.8.0` solves the problem.

Btw. A very similar problem is described in https://github.com/iterative/dvc/issues/6899 - and fixed in upstream?!

```
import unittest


class test_list_bucket(unittest.TestCase):

    test_bucket = "test-bucket-achim"
    test_prefix = "/"

    def test_s3fs(self):
        import s3fs
        fs = s3fs.S3FileSystem()
        fs.ls(f"s3://{self.test_bucket}/{self.test_prefix}")

    def test_boto3(self):

        import boto3
        s3c = boto3.client("s3")
        s3c.list_objects(Bucket=self.test_bucket, Prefix=self.test_prefix)
```

**Comment by martindurant** [comment] 2021-11-22 13:58
The linked issue seems to be around azure-blob, not s3 - are you sure it is similar? If yes, please tag a couple of the people there to see if they can help.

Note that aiohttp is now at 3.8.1; can you generate a set of versions which do/do not work?

**Comment by achimgaedke** [comment] 2021-11-22 18:47
Hey @martindurant 

Re DVC issue: I noticed that. It is similar from an "end-user" perspective, using DVC and s3fs and getting the same error. I've added the word "surprisingly", I can't say whether this is a red herring.

Re version comparison: The setup I'm debugging is a bit more complex, so I will boil it down over the next day or two. Here a diff between the two quite convoluted conda environments:

```
diff s3test_pass.txt s3test_fail.txt 
11c11
< aiohttp                   3.7.4.post0      py39h3811e60_1    conda-forge
---
> aiohttp                   3.8.1            py39h3811e60_0    conda-forge
13a14
> aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
21c22
< async-timeout             3.0.1                   py_1000    conda-forge
---
> async-timeout             4.0.1              pyhd8ed1ab_0    conda-forge
108a110
> frozenlist                1.2.0            py39h3811e60_1    conda-forge
``` 

The passing environment contains the `aiohttp<3.8.0` requirement.

**Comment by raybellwaves** [comment] 2021-11-22 21:23
If you pip install s3fs does it works? (https://github.com/fsspec/s3fs/pull/553#issue-1055649151 for reference)

**Comment by achimgaedke** [comment] 2021-11-22 21:33
I had problems with the pip installation as well - but (both pip and conda) it worked when having only the minimal environment definition with the latest versions of all packages.

So, that's why I intend to try to provide an environment definition soon... just having not enough time at hand, sorry.

**Comment by achimgaedke** [comment] 2021-11-23 00:18
A minimal conda environment to reproduce the error. NB dvc and the version numbers seem to be critical.
The tests are run wiht mamba 0.18.1 and ubuntu 20.04.

```
name: s3test
channels:
  - conda-forge
  - nodefaults
dependencies:
  # move this
  # - aiohttp<3.8.0
  - boto3>=1.17
  - dvc>=2.8
  - dvc-s3>=2.8
  - python>=3.9
  - s3fs>=2021.0.0
```

The difference between pass and fail are:
```
$ diff s3test_pass.txt s3test_fail.txt 
7c7
< aiohttp                   3.7.4.post0     py310h6acc77f_1    conda-forge
---
> aiohttp                   3.8.1           py310h6acc77f_0    conda-forge
9a10
> aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
11c12
< async-timeout             3.0.1                   py_1000    conda-forge
---
> async-timeout             4.0.1              pyhd8ed1ab_0    conda-forge
55a57
> frozenlist                1.2.0           py310h6acc77f_1    conda-forge
```

The environment lists are attached:
* [s3test_pass.txt](https://github.com/fsspec/s3fs/files/7585159/s3test_pass.txt)
* [s3test_fail.txt](https://github.com/fsspec/s3fs/files/7585160/s3test_fail.txt)

**Comment by achimgaedke** [comment] 2021-11-23 00:22
A week ago I had problems with a pip installed s3fs. I can't reproduce the error with a similar pip requirements file.

The platform is ubuntu 20.04 with python3.9 (installed with conda).

```
boto3>=1.17
dvc[s3]>=2.8
s3fs>=2021.0.0
```

**Comment by achimgaedke** [comment] 2021-11-23 02:14
```
name: s3test
channels:
  - conda-forge
dependencies:
  - mamba
  - pip
  - python>=3.9,<3.10
  - wheel
  - pip:
    - dvc[s3,ssh]>=2.8
    - s3fs>=2021.0.0
```

fails as well

**Comment by martindurant** [comment] 2021-11-23 02:31
So only ever in conjunction with dvc?

**Comment by achimgaedke** [comment] 2021-11-23 03:13
@martindurant - yes for me. @jmleoni any insight in this?

I believe it is due to a weird and unfortunate combination action of libraries and their versions, so I try to help with reporting...

**Comment by jmleoni** [comment] 2021-11-23 10:31
We are trying to reproduce the issue in isolation, from our application with no luck so far.
What I can confirm is that it is not working with either aiohttp 3.8.0 nor 3.8.1 but it works fine with version 3.7.4.post0
I will keep you posted if we have a setup that can be exported and that let us reproduce the issue in a consistent manner

**Comment by TheoJammes** [comment] 2021-11-29 11:03
Hello, 
I work with @jmleoni and we tried investigating the issue. Unfortunately we could not reproduce with a minimal python script that just reads a parquet file, but it occurs 100% with our python project which has a rather big code base.

By plugging a debugger to the python running on batch EC2 we've discovered that the error does not appear when the code has been halted by breakpoints, due to this we suspect there might be a race condition when AioCredentialsResolver#load_credentials() is called (see screenshot). 
When there are no breakpoints it returns null but if we put a breakpoint after the async call is made, then it returns a value.

![image](https://user-images.githubusercontent.com/80251874/143856701-29ef1142-83b2-43ed-a9ab-04073b401a27.png)

**Comment by martindurant** [comment] 2021-11-29 14:10
Thanks for the investigation and interesting finding. I'm not certain what to do about it. It is it a timing thing indeed, it suggests we can merely retry on credentials error, or explicitly wait for the credentials provider above to complete, before attempting anything else.

**Comment by raybellwaves** [comment] 2021-12-01 19:21
@jmleoni any idea if this is fixed with the latest s3fs?
can confirm my issue (reported in https://github.com/fsspec/s3fs/pull/554#issue-1055654134) is fixed. However, i'll confess when I installed today in brought in 2021.11.0.

**Comment by garibarba** [comment] 2021-12-03 14:54
> We are trying to reproduce the issue in isolation, from our application with no luck so far. What I can confirm is that it is not working with either aiohttp 3.8.0 nor 3.8.1 but it works fine with version 3.7.4.post0 I will keep you posted if we have a setup that can be exported and that let us reproduce the issue in a consistent manner

Indeed `pip install "aiohttp<3.8"` fixes it.

To reproduce in my case:
Using Python 3.9.7
`pip install dvc[s3]`

Then:
```python
import s3fs
fs = s3fs.S3FileSystem()
fs.ls('my-bucket')
```

**Comment by achimgaedke** [comment] 2021-12-05 00:24
Hey @garibarba - thanks for reproducing. I ran the same commands with python3.8, python3.9 and python3.10 - and "it works for me" **without `"aiohttp<3.8"`**

```
python3 -m venv s3test
./s3test/bin/pip install -U pip wheel
./s3test/bin/pip install s3fs dvc[s3]
./s3test/bin/python
```

and then executing the commands - replacing `my-bucket` with an existing bucket I have access permissions to.

```
import s3fs
fs = s3fs.S3FileSystem()
fs.ls('my-bucket')
```

Result: I get the bucket listing as expected.

I repeated the setup from https://github.com/fsspec/s3fs/issues/558#issuecomment-976032199 and it works as well. - I am not convinced whther the 

```
diff s3test_updated_pass.txt s3test_fail.txt 
30c30,31
< charset-normalizer        2.0.8              pyhd8ed1ab_0    conda-forge
---
> chardet                   4.0.0           py310hff52083_2    conda-forge
> charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
34c35
< cryptography              36.0.0          py310h685ca39_0    conda-forge
---
> cryptography              35.0.0          py310h685ca39_2    conda-forge
37c38
< diskcache                 5.3.0              pyhd8ed1ab_0    conda-forge
---
> diskcache                 5.2.1              pyh44b312d_0    conda-forge
53c54
< fonttools                 4.28.3          py310h6acc77f_0    conda-forge
---
> fonttools                 4.28.1          py310h6acc77f_0    conda-forge
71c72
< harfbuzz                  3.1.2                hb4a5f5f_0    conda-forge
---
> harfbuzz                  3.1.1                hb4a5f5f_1    conda-forge
112c113
< mailchecker               4.1.3              pyhd8ed1ab_0    conda-forge
---
> mailchecker               4.1.0              pyhd8ed1ab_0    conda-forge
130c131
< phonenumbers              8.12.38            pyhd8ed1ab_0    conda-forge
---
> phonenumbers              8.12.37            pyhd8ed1ab_0    conda-forge
155,156c156,157
< requests                  2.26.0             pyhd8ed1ab_1    conda-forge
< rich                      10.15.2         py310hff52083_0    conda-forge
---
> requests                  2.26.0             pyhd8ed1ab_0    conda-forge
> rich                      10.14.0         py310hff52083_1    conda-forge
161,162c162,163
< scipy                     1.7.3           py310hea5193d_0    conda-forge
< setuptools                59.4.0          py310hff52083_0    conda-forge
---
> scipy                     1.7.2           py310hea5193d_0    conda-forge
> setuptools                59.2.0          py310hff52083_0    conda-forge
164c165
< shtab                     1.5.2              pyhd8ed1ab_0    conda-forge
---
> shtab                     1.5.0              pyhd8ed1ab_0    conda-forge
167c168
< sqlite                    3.37.0               h9cd32fc_0    conda-forge
---
> sqlite                    3.36.0               h9cd32fc_2    conda-forge
```

My next step: I will wait for the December s3fs release and test it in the full data-science tool chain.

Thanks `s3fs` team for hanging in there... what an annoying bug!

**Comment by garibarba** [comment] 2021-12-05 01:18
@achimgaedke interesting. In my case there is a chance of some non-standard network configuration. I believe my access to S3 is through a VPC endpoint, but there might be other specific configs. I've seen some relatable 3.8.0 issues such as https://github.com/aio-libs/aiohttp/issues/6227 or https://github.com/aio-libs/aiohttp/issues/6239 but I cannot put my finger on it.

**Comment by achimgaedke** [comment] 2021-12-05 01:55
> My next step: I will wait for the December s3fs release and test it in the full data-science toolchain.

Doesn't work with the more complex setup... so still something wrong.

**Comment by martindurant** [comment] 2021-12-05 18:34
Since we are likely to bump the req, can you try with aiiohttp>4?

**Comment by rom1504** [comment] 2022-02-09 12:21
> Thanks for the investigation and interesting finding. I'm not certain what to do about it. It is it a timing thing indeed, it suggests we can merely retry on credentials error, or explicitly wait for the credentials provider above to complete, before attempting anything else.

Having such a retry option (and even maybe putting it at like 5 retry by default) would be really appreciated. I just hit an intermittent such auth issue and it's a bit ugly of having to handle that in user code

**Comment by achimgaedke** [comment] 2022-05-05 11:36
There has been some more work on this bug. `aiobotocre PR https://github.com/aio-libs/aiobotocore/pull/934 looks promising. Consider upgrading requirements to `aiobotocore~=2.3.0` when released.

**Comment by martindurant** [comment] 2022-05-05 13:16
@achimgaedke , would you like to make a PR with that change, when available?

**Closed** 2022-05-06 20:20 UTC

**Comment by jmleoni** [comment] 2022-05-20 09:47
@achimgaedke I didn't take the opportunity yet, but many thanks to you for fixing on this issue, you are a life saver !

**Comment by achimgaedke** [comment] 2022-05-20 09:55
I waited for almost half a year for someone else to dig it up. Took me 4 hours, 30 min to fix and then another x hours over 3 weeks to push it through the software supply chain... now conda-forge is the last one missing...

Thanks for thanking, @jmleoni .

**Comment by achimgaedke** [comment] 2022-05-20 12:09
See https://github.com/conda-forge/s3fs-feedstock/pull/55
